#!/bin/bash
# Assembles dist/ReportGitHub.app from the Xcode project (generated by XcodeGen;
# see project.yml).
#
# Built with xcodebuild rather than `swift build` + hand assembly: SwiftPM's
# generated Bundle.module accessor for executable products probes only the
# app-bundle ROOT (where codesign forbids loose bundles) and the absolute
# build-time path, so a hand-assembled app fatalErrors at launch on every
# machine except the one that built it — for our Kit bundle and Highlightr's
# alike. Xcode's accessor probes Contents/Resources, where xcodebuild embeds
# every package resource bundle.
#
# Signing: ad-hoc by default (local use). For a Developer ID build, set
# SIGN_IDENTITY="Developer ID Application" and DEVELOPMENT_TEAM=<team id>; the
# app, nested package bundles, and frameworks are then signed by xcodebuild with
# a secure timestamp under the hardened runtime, ready for notarization. CI
# wires this up on tag releases (see .github/workflows/release.yml).
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${1:-release}"
APP="dist/ReportGitHub.app"
VERSION="${VERSION:-1.0.0}"
DERIVED=".build/DerivedData"
SIGN_IDENTITY="${SIGN_IDENTITY:--}"

case "$CONFIG" in
  release) XCODE_CONFIG="Release" ;;
  debug)   XCODE_CONFIG="Debug" ;;
  *) echo "unknown config: $CONFIG (use release|debug)" >&2; exit 1 ;;
esac

SIGN_ARGS=(CODE_SIGN_IDENTITY="$SIGN_IDENTITY")
if [[ "$SIGN_IDENTITY" != "-" ]]; then
  : "${DEVELOPMENT_TEAM:?DEVELOPMENT_TEAM is required when SIGN_IDENTITY is not ad-hoc}"
  # Manual signing: the project (and its SwiftPM resource-bundle targets) default
  # to automatic signing, which conflicts with a manually specified Developer ID
  # identity. Developer ID direct distribution needs no provisioning profile.
  SIGN_ARGS+=(
    CODE_SIGN_STYLE=Manual
    PROVISIONING_PROFILE_SPECIFIER=""
    DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"
    OTHER_CODE_SIGN_FLAGS="--timestamp"
    # Suppress the get-task-allow debug entitlement; notarization rejects it.
    CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO
  )
fi

xcodebuild -project ReportGitHub.xcodeproj -scheme ReportGitHubApp \
  -configuration "$XCODE_CONFIG" -derivedDataPath "$DERIVED" \
  MARKETING_VERSION="$VERSION" CURRENT_PROJECT_VERSION="$VERSION" \
  "${SIGN_ARGS[@]}" \
  build

BUILT="$DERIVED/Build/Products/$XCODE_CONFIG/ReportGitHub.app"
[[ -d "$BUILT" ]] || { echo "missing $BUILT" >&2; exit 1; }
# Where the Xcode-generated Bundle.module accessor will look at runtime.
[[ -d "$BUILT/Contents/Resources/ReportGitHub_ReportGitHubKit.bundle" ]] || {
  echo "ReportGitHubKit resource bundle not embedded in app" >&2; exit 1
}
[[ -d "$BUILT/Contents/Resources/Highlightr_Highlightr.bundle" ]] || {
  echo "Highlightr resource bundle not embedded in app" >&2; exit 1
}

rm -rf "$APP"
mkdir -p dist
ditto "$BUILT" "$APP"

if [[ "$SIGN_IDENTITY" == "-" ]]; then
  # Ad-hoc re-sign for local use; nested code was already ad-hoc signed by the build.
  codesign --force --sign - "$APP"
fi
# For a Developer ID build, ditto preserves xcodebuild's signature (app + nested
# bundles, hardened runtime, secure timestamp); no re-sign needed.
echo "Built $APP (config: $XCODE_CONFIG, version: $VERSION, identity: $SIGN_IDENTITY)"
